name: Sync Website Repo

on:
  push:
    branches:
      - master

jobs:
  sync-website:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v4
        with:
          repository: isaacbernat/netflix-to-srt-web
          path: website
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Development Repo
        uses: actions/checkout@v4
        with:
          repository: isaacbernat/netflix-to-srt
          path: dev_repo

      - name: Check for Changes
        id: check-changes
        run: |
          cp -r dev_repo/web/* website/
          cd website
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up SSH Key
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"

      - name: Configure Git
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          cd website
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and Push Changes to Website Repo
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          cd website
          git add .
          git commit -m "Updated website from dev repo"
          git push git@github.com:isaacbernat/netflix-to-srt-web.git main
